// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYStdMjXbCKUT9SsDA7lSQSPZ2ogQbiDg',
    appId: '1:138306259528:web:f4071a329c5577f97f667d',
    messagingSenderId: '138306259528',
    projectId: 'notes-ca8bb',
    authDomain: 'notes-ca8bb.firebaseapp.com',
    databaseURL: 'https://notes-ca8bb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'notes-ca8bb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNR3rlkBP_YaQ3SBla_RRX5DjIkiacj94',
    appId: '1:138306259528:android:4eaf2a1ec977a8d37f667d',
    messagingSenderId: '138306259528',
    projectId: 'notes-ca8bb',
    databaseURL: 'https://notes-ca8bb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'notes-ca8bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAozOEJ3qAwnfVLxFfs-_okWz-yk2w6xGQ',
    appId: '1:138306259528:ios:90a693575a42e16f7f667d',
    messagingSenderId: '138306259528',
    projectId: 'notes-ca8bb',
    databaseURL: 'https://notes-ca8bb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'notes-ca8bb.appspot.com',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAozOEJ3qAwnfVLxFfs-_okWz-yk2w6xGQ',
    appId: '1:138306259528:ios:cdf9ac91d25a32237f667d',
    messagingSenderId: '138306259528',
    projectId: 'notes-ca8bb',
    databaseURL: 'https://notes-ca8bb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'notes-ca8bb.appspot.com',
    iosBundleId: 'com.example.mynotes.RunnerTests',
  );
}
